/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "apollo_constants.h"

namespace apollo { namespace rpc { namespace api {

const apolloConstants g_apollo_constants;

apolloConstants::apolloConstants() {
}

}}} // namespace

