/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef apollo_CONSTANTS_H
#define apollo_CONSTANTS_H

#include "apollo_types.h"

namespace apollo { namespace rpc { namespace api {

class apolloConstants {
 public:
  apolloConstants();

};

extern const apolloConstants g_apollo_constants;

}}} // namespace

#endif
